# DEPRECATED
# from 128 -> 256 ffhq config (adapted from bsr_sr & ffhq256_sr.yaml, official source config superresolution)
model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0155
    log_every_t: 100
    timesteps: 1000 # original 1000
    loss_type: l2
    first_stage_key: image
    cond_stage_key: LR_image
    image_size: 128 # original 64
    channels: 3
    cond_stage_trainable: false
    concat_mode: true
    monitor: val/loss
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 128 # original 64
        in_channels: 6
        out_channels: 3
        model_channels: 160
        attention_resolutions:
          - 16
          - 8
        num_res_blocks: 2
        channel_mult:
          - 1
          - 2
          - 2
          - 4
        num_head_channels: 32
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        ckpt_path: /home/zhren/Charlie/latent-diffusion/models/first_stage_models/vq-f8/model.ckpt
        embed_dim: 4
        n_embed: 16384
        monitor: val/rec_loss
        ddconfig:
          double_z: false
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
            - 1
            - 2
            - 2
            - 4
          num_res_blocks: 2
          attn_resolutions:
            - 32
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: torch.nn.Identity
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 5
    wrap: false
    train:
      target: taming.data.ffhq.FFHQSRTrain
      params:
        size: 256
        degradation: bsrgan_light
        downscale_f: 2
        min_crop_f: 0.5
        max_crop_f: 1.0
        random_crop: true
    validation:
      target: taming.data.ffhq.FFHQSRValidation
      params:
        size: 256
        degradation: bsrgan_light
        downscale_f: 2
        min_crop_f: 0.5
        max_crop_f: 1.0
        random_crop: true
